<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SolverCli</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Assets\Scripts\Engine\*.cs" />
  </ItemGroup>
</Project>
